LeaveManagementSystemTW.MVC/Controllers/LeaveTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LeaveManagementSystemTW.Services;
using LeaveManagementSystemTW.Services.Models.LeaveTypes;
using Microsoft.AspNetCore.Authorization;
using LeaveManagementSystemTW.Services.Common;

namespace LeaveManagementSystemTW.MVC.Controllers
{
    [Authorize(Roles =Roles.Administrator)]
    public class LeaveTypesController : Controller
    {
        //private readonly LeaveManagementSystemDbContext _context;
        //private readonly IMapper _mapper;
        private readonly ILeaveTypesService _leaveTypesService;

        public LeaveTypesController(ILeaveTypesService leaveTypesService)
        {
            _leaveTypesService = leaveTypesService;
        }

        // GET: LeaveTypes
        public async Task<IActionResult> Index()
        {
            var dataDtos = await _leaveTypesService.GetAllAsync();
            return View(dataDtos);
        }

        // GET: LeaveTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var leaveTypeDto = await _leaveTypesService.GetAsync<LeaveTypeReadOnlyVM>(id.Value);
            if (leaveTypeDto == null)
            {
                return NotFound();
            }
            return View(leaveTypeDto);
        }

        // GET: LeaveTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: LeaveTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Days")] LeaveTypeCreateVM leaveTypeVM)
        {
            if ( await _leaveTypesService.LeaveTypeNameExistsAsync(leaveTypeVM.Name))
            {
                ModelState.AddModelError("LeaveType", $"Leavetype {leaveTypeVM.Name} already exists");
            }
            if (ModelState.IsValid)
            {
                await _leaveTypesService.CreateAsync(leaveTypeVM);
                return RedirectToAction(nameof(Index));
            }
            return View(leaveTypeVM);
        }



        // GET: LeaveTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveTypeEditVM = await _leaveTypesService.GetAsync<LeaveTypeEditVM>(id.Value);
            if (leaveTypeEditVM == null)
            {
                return NotFound();
            }

            return View(leaveTypeEditVM);
        }

        // POST: LeaveTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Days")] LeaveTypeEditVM leaveTypeEditVM)
        {
            if (id != leaveTypeEditVM.Id)
            {
                return NotFound();
            }

            if (await _leaveTypesService.LeaveTypeNameExistsForEditAsync(leaveTypeEditVM))
            {
                ModelState.AddModelError("LeaveType", $"Leavetype {leaveTypeEditVM.Name} already exists");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _leaveTypesService.EditAsync(leaveTypeEditVM);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_leaveTypesService.LeaveTypeExists(leaveTypeEditVM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(leaveTypeEditVM);
        }

        // GET: LeaveTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveType = await _leaveTypesService.GetAsync<LeaveTypeReadOnlyVM>(id.Value);
            if (leaveType == null)
            {
                return NotFound();
            }

            return View(leaveType);
        }

        // POST: LeaveTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var leaveType = await _leaveTypesService.GetAsync<LeaveTypeReadOnlyVM>(id);
            if (leaveType != null)
            {
                await _leaveTypesService.RemoveAsync(leaveType.Id);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

LeaveManagementSystemTW.MVC/Controllers/PeriodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LeaveManagementSystem.Data;
using LeaveManagementSystem.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using LeaveManagementSystemTW.Services.Common;

namespace LeaveManagementSystemTW.MVC.Controllers;

[Authorize(Roles = Roles.Administrator)]
public class PeriodsController : Controller
{
    // not implemented a service here.
    // the other LeaveType was slightly more complex
    // trainer decides against a service here because of training overhead

    private readonly LeaveManagementSystemDbContext _context;

    public PeriodsController(LeaveManagementSystemDbContext context)
    {
        _context = context;
    }

    // GET: Periods
    public async Task<IActionResult> Index()
    {
        return View(await _context.Periods.ToListAsync());
    }

    // GET: Periods/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var period = await _context.Periods
            .FirstOrDefaultAsync(m => m.Id == id);
        if (period == null)
        {
            return NotFound();
        }

        return View(period);
    }

    // GET: Periods/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Periods/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Name,StartDate,EndDate,Id")] Period period)
    {
        if (ModelState.IsValid)
        {
            _context.Add(period);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(period);
    }

    // GET: Periods/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var period = await _context.Periods.FindAsync(id);
        if (period == null)
        {
            return NotFound();
        }
        return View(period);
    }

    // POST: Periods/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Name,StartDate,EndDate,Id")] Period period)
    {
        if (id != period.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(period);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PeriodExists(period.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(period);
    }

    // GET: Periods/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var period = await _context.Periods
            .FirstOrDefaultAsync(m => m.Id == id);
        if (period == null)
        {
            return NotFound();
        }

        return View(period);
    }

    // POST: Periods/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var period = await _context.Periods.FindAsync(id);
        if (period != null)
        {
            _context.Periods.Remove(period);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool PeriodExists(int id)
    {
        return _context.Periods.Any(e => e.Id == id);
    }
}

LeaveManagementSystemTW.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LeaveTime</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LeaveManagementSystemTW.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark  border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LeaveTime</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(Roles.Administrator))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="LeaveTypes" asp-action="Index">Leave Types</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Periods" asp-action="Index">Periods</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="LeaveAllocation" asp-action="Index">Employees</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="LeaveRequests" asp-action="ListRequests">All Requests</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated){
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="LeaveAllocation" asp-action="Details">View allocations</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - LeaveManagementSystemTW.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>